package com.example.springshiro.domain.entity;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.role_name
     *
     * @mbggenerated
     */
    private String role_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.user_id
     *
     * @mbggenerated
     */
    private Integer user_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.id
     *
     * @return the value of Role.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.id
     *
     * @param id the value for Role.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.role_name
     *
     * @return the value of Role.role_name
     *
     * @mbggenerated
     */
    public String getRole_name() {
        return role_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.role_name
     *
     * @param role_name the value for Role.role_name
     *
     * @mbggenerated
     */
    public void setRole_name(String role_name) {
        this.role_name = role_name == null ? null : role_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.user_id
     *
     * @return the value of Role.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.user_id
     *
     * @param user_id the value for Role.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }
}